version: "3"
services:
  gateway:
    build:
      context: ./gateway
  users:
    build:
      context: ./users
  flow:
    build:
      context: ./flow
  temperature:
    build:
      context: ./iot/temperature
  wemo:
    build:
      context: ./iot/wemo
