# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wemo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/wemo.proto\x12\x04wemo\"1\n\x13\x43reateDeviceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\'\n\x14\x43reateDeviceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x16GetDeviceStatusRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x17GetDeviceStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"6\n\x16SetDeviceStatusRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"8\n\x17SetDeviceStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xf4\x01\n\x0bWemoService\x12\x45\n\x0c\x43reateDevice\x12\x19.wemo.CreateDeviceRequest\x1a\x1a.wemo.CreateDeviceResponse\x12N\n\x0fGetDeviceStatus\x12\x1c.wemo.GetDeviceStatusRequest\x1a\x1d.wemo.GetDeviceStatusResponse\x12N\n\x0fSetDeviceStatus\x12\x1c.wemo.SetDeviceStatusRequest\x1a\x1d.wemo.SetDeviceStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.wemo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATEDEVICEREQUEST']._serialized_start=26
  _globals['_CREATEDEVICEREQUEST']._serialized_end=75
  _globals['_CREATEDEVICERESPONSE']._serialized_start=77
  _globals['_CREATEDEVICERESPONSE']._serialized_end=116
  _globals['_GETDEVICESTATUSREQUEST']._serialized_start=118
  _globals['_GETDEVICESTATUSREQUEST']._serialized_end=156
  _globals['_GETDEVICESTATUSRESPONSE']._serialized_start=158
  _globals['_GETDEVICESTATUSRESPONSE']._serialized_end=199
  _globals['_SETDEVICESTATUSREQUEST']._serialized_start=201
  _globals['_SETDEVICESTATUSREQUEST']._serialized_end=255
  _globals['_SETDEVICESTATUSRESPONSE']._serialized_start=257
  _globals['_SETDEVICESTATUSRESPONSE']._serialized_end=313
  _globals['_WEMOSERVICE']._serialized_start=316
  _globals['_WEMOSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
